import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "uhhhh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <header>

        </header>

        <main className="flex flex-1 items-center justify-center">{children}</main>

        <footer className="pb-7 text-xl flex justify-center">
          <Link className="px-2" href="/">Home</Link>
          <Link className="px-2" href="/stress">Stress Meter</Link>
        </footer>

      </body>
    </html>
  );
}
